// Code generated by "stringer -type=FrameType"; DO NOT EDIT.

package http2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DATA-0]
	_ = x[HEADERS-1]
	_ = x[PRIORITY-2]
	_ = x[RSTSTREAM-3]
	_ = x[SETTINGS-4]
	_ = x[PUSHPROMISE-5]
	_ = x[PING-6]
	_ = x[GOAWAY-7]
	_ = x[WINDOWUPDATE-8]
	_ = x[CONTINUATION-9]
}

const _FrameType_name = "DATAHEADERSPRIORITYRSTSTREAMSETTINGSPUSHPROMISEPINGGOAWAYWINDOWUPDATECONTINUATION"

var _FrameType_index = [...]uint8{0, 4, 11, 19, 28, 36, 47, 51, 57, 69, 81}

func (i FrameType) String() string {
	if i >= FrameType(len(_FrameType_index)-1) {
		return "FrameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FrameType_name[_FrameType_index[i]:_FrameType_index[i+1]]
}
